<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Pixoar.Core</AssemblyName>
    <RootNamespace>Pixoar.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU"
                      Version="14.15.0"
                      GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(PkgMagick_NET-Q8-AnyCPU)\Notice.txt')">
    <Content Include="$(PkgMagick_NET-Q8-AnyCPU)\Notice.txt"
             Link="licenses\Magick.NET-Notice.txt"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
